#!/bin/sh

cd src

if  ps aux | grep '[b]btcs_webserve' 
then 
   echo 'btcs_webserve already running'
else 
   echo 'Starting btcs_webserve ' 
   nohup ./btcs_webserve.py 3000 2>&1 >> ../log/btcs-webserve.log  &
fi

if  ps aux | grep '[p]rocess_all.py'
then 
   echo 'Process_all already running'
else 
   echo 'Starting process_all..' 
   nohup ./process_all.py &
fi

cd ..

